[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.gd", "php82Extensions.curl", "php82Extensions.openssl", "php82Extensions.zip"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-reqs"]

[variables]
PHP_VERSION = "8.2"
COMPOSER_ALLOW_SUPERUSER = "1"

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."